name: 'rollback test'

env:
  DOCKER_BUILDKIT: 1
  GOMEMLIMIT: 2GiB

on:
  workflow_dispatch:
    inputs:
      N-1_version:
        description: 'Previous application version'
        required: true
      N_version:
        description: 'Next application version'
        required: true

  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  rollback_test:
    runs-on: ubuntu-latest
    steps:
      - name: Define versions for PR
        id: pr_parameters
        if: github.event_name == 'pull_request'
        run: |
          echo "N_MINUS_VERSION={GITHUB_BASE_REF}" >> $GITHUB_ENV
          echo "N_VERSION={GITHUB_HEAD_REF}" >> $GITHUB_ENV
      - name: Define versions for manual run
        id: manual_parameters
        if: github.event_name != 'pull_request'
        env:
          INPUT_1: ${{github.event.inputs.N-1_version}}
          INPUT_2: ${{github.event.inputs.N_version}}
        run: |
          echo $INPUT_1
          echo $INPUT_2
          echo "N_MINUS_VERSION=$INPUT_1" >> $GITHUB_ENV
          echo "N_VERSION=$INPUT_2" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        name: 'checkout N-1'
        with:
           ref: ${{ env.N_MINUS_VERSION }}
           path: 'n-1'
      - uses: actions/checkout@v4
        name: 'checkout N'
        with:
           ref: ${{ env.N_VERSION }}
           path: 'n'
